-- CREAR EN EL ESQUEMA AVANZADO USSO ESTAS DOS TABLAS
 
 CREATE TABLE "NAOS_SUITE_PARAM_EXTENSION"."CRITERIOS_PARAMETROS" 
   (	"ID_CRITERIO" NUMBER(19,0) NOT NULL ENABLE, 
	"ID_SERVICIO" NUMBER(19,0) NOT NULL ENABLE, 
	"ID_OPERACION" NUMBER(19,0) NOT NULL ENABLE, 
	"TX_TAREA" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ID_SERVICEVERSION" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CRITERIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ; -- -- CON EL USUARIO con las características y capacidades para la creación y mantenimiento de los objetos del esquema AVANZADO
  



CREATE TABLE "NAOS_SUITE_PARAM_EXTENSION"."PARAMETROS" 
   (	"ID_PARAMETROS" NUMBER(19,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(400 BYTE) NOT NULL ENABLE, 
	"OBLIGATORIO" NUMBER(1,0) NOT NULL ENABLE, 
	"INHABILITADO" NUMBER(1,0) NOT NULL ENABLE, 
	"NU_FKCRITERIOS" NUMBER(19,0) NOT NULL ENABLE, 
	"TX_ORDEN" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "PARAMETROS_PK" PRIMARY KEY ("ID_PARAMETROS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CRITERIOS" FOREIGN KEY ("NU_FKCRITERIOS")
	  REFERENCES "NAOS_SUITE_PARAM_EXTENSION"."CRITERIOS_PARAMETROS" ("ID_CRITERIO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ; -- -- CON EL USUARIO con las características y capacidades para la creación y mantenimiento de los objetos del esquema AVANZADO
 

  CREATE OR REPLACE TRIGGER "NAOS_SUITE_PARAM_EXTENSION"."TR_PARAMETROS" 
BEFORE INSERT ON PARAMETROS
FOR EACH ROW
BEGIN
SELECT SQ_PARAMETROS.NEXTVAL INTO :NEW.ID_PARAMETROS FROM DUAL;
END; -- -- CON EL USUARIO con las características y capacidades para la creación y mantenimiento de los objetos del esquema AVANZADO
/
ALTER TRIGGER "NAOS_SUITE_PARAM_EXTENSION"."TR_PARAMETROS" ENABLE;
