
--OBTENER LISTADO DE CITAS DE UN CONTENEDOR DE CALENDARIO 
SELECT * FROM CITA 
JOIN ELEMENTO_ICAL ON CITA.ID_CITA = ELEMENTO_ICAL.ID_ELEMENTO_ICAL
JOIN ELEMENTO_PIM ON ELEMENTO_ICAL.ID_ELEMENTO_ICAL = ELEMENTO_PIM.ID_ELEMENTO
JOIN CONTENEDOR ON ELEMENTO_PIM.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
WHERE CONTENEDOR.ID_CONTENEDOR = '21'



--OBTENER LISTADO DE CONTACTOS DE UN CONTENEDOR DE CALENDARIO 

SELECT * FROM CONTACTO
JOIN ELEMENTO_PIM ON CONTACTO.ID_CONTACTO = ELEMENTO_PIM.ID_ELEMENTO
JOIN CONTENEDOR ON ELEMENTO_PIM.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
WHERE CONTENEDOR.ID_CONTENEDOR = '31'


--LISTADO DE TAREAS DE UN CONTENEDOR DE CALENDARIO

SELECT * FROM TAREA
JOIN ELEMENTO_ICAL ON TAREA.ID_TAREA = ELEMENTO_ICAL.ID_ELEMENTO_ICAL
JOIN ELEMENTO_PIM ON ELEMENTO_ICAL.ID_ELEMENTO_ICAL = ELEMENTO_PIM.ID_ELEMENTO
JOIN CONTENEDOR ON ELEMENTO_PIM.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
WHERE CONTENEDOR.ID_CONTENEDOR = '27'


-- LISTADO DE CATEGORÍAS EXISTENTES PARA EL CALENDARIO DE UN USUARIO

SELECT * FROM CATEGORIA
JOIN CONTENEDOR ON CATEGORIA.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
JOIN PREFERENCIA ON CONTENEDOR.ID_CONTENEDOR = PREFERENCIA.ID_CALENDARIO
JOIN USUARIO ON PREFERENCIA.ID_PREFERENCIA = USUARIO.ID_PREFERENCIA
WHERE USUARIO.ID_USUARIO = '19'

--LISTADO DE CATEGORIAS EXISTENTES PARA LA LIBRETA DE CONTACTOS DE UN USUARIO

SELECT * FROM CATEGORIA
JOIN CONTENEDOR ON CATEGORIA.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
JOIN PREFERENCIA ON CONTENEDOR.ID_CONTENEDOR = PREFERENCIA.ID_LIBRETA
JOIN USUARIO ON PREFERENCIA.ID_PREFERENCIA = USUARIO.ID_PREFERENCIA
WHERE USUARIO.ID_USUARIO = '19'

--LISTADO DE CATEGORIAS EXISTENTES PARA LA BANDEJA DE TAREAS DE UN USUARIO

SELECT * FROM CATEGORIA
JOIN CONTENEDOR ON CATEGORIA.ID_CONTENEDOR = CONTENEDOR.ID_CONTENEDOR
JOIN PREFERENCIA ON CONTENEDOR.ID_CONTENEDOR = PREFERENCIA.ID_REGISTRO
JOIN USUARIO ON PREFERENCIA.ID_PREFERENCIA = USUARIO.ID_PREFERENCIA
WHERE USUARIO.ID_USUARIO = '19'

-- PERMISOS QUE UN USUARIO TIENE CONCEDIDOS (SUSCRIPCIONES)
SELECT * FROM SUBSCRIPCION 
JOIN PREFERENCIA ON SUBSCRIPCION.ID_PREFERENCIA = PREFERENCIA.ID_PREFERENCIA
JOIN USUARIO ON PREFERENCIA.ID_PREFERENCIA = USUARIO.ID_PREFERENCIA
WHERE USUARIO.ID_USUARIO = '19'