# Default setup is given for MySQL with ruby1.9. If you're running Redmine
# with MySQL and ruby1.8, replace the adapter name with `mysql`.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: mysql2
  database: redmineDES
#  host: 10.240.242.4
  host: 10.240.242.50
  username: user_redmine_11
  password: pa55_redm1ne_11
  encoding: utf8
  reconnect: true
